#Deployment will make use of Docker Image which we created earlier and pushed to DockerHub.

apiVersion: apps/v1
kind: Deployment
metadata:
        name: mydeployment
spec:
        selector:
                matchLabels:
                        app: cloud
        replicas: 3
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxSurge: 1
                        maxUnavailable: 1
        template:
                metadata:
                        name: mypod
                        labels:
                                app: cloud
                spec:
                        containers:
                                - name: mycontainer
                                  image: pbhavsar73/kubernetesproject            #This is the Docker Image which we created earlier from Dockerfile and pushed to DockerHub.
                                  imagePullPolicy: Always
                                  ports:
                                          - containerPort: 80
                        tolerations:                                             #For Single Node Cluster only (MiniKube).
                                - effect: "NoExecute"
                                  key: "node.kubernetes.io/not-ready"
                                  operator: "Exists"
                                - effect: "NoExecute"
                                  key: "node.kubernetes.io/unreachable"
                                  operator: "Exists"
