apiVersion: v1
kind: Service
metadata:
        name: myservice
        labels:
                app: cloud
spec:
        selector:
                app: cloud
        type: LoadBalancer
        ports:
                - port: 8080
                  targetPort: 80
                  nodePort: 31200
